# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-slim

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm ci \
    && npm run build \
    && npm prune --production

# Copy other necessary files
COPY README.md LICENSE ./

# Expose no port since it's stdio-based

# Default command
CMD ["node", "dist/index.js"]
